server:
  port: 9999

spring:
  application:
    name: quick-boot
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev_demo
    password: devDemo123!XX
    url: jdbc:mysql://127.0.0.1:3306/quick-boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: accessToken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: true

magic-api:
  web: /magic/web
  prefix: /api
  editor-config: classpath:./magic-editor-config.js
  resource:
    type: database # 配置存储在数据库中
    tableName: magic_api_file # 数据库中的表名
    readonly: false # 是否是只读模式
  backup: #备份相关配置
    enable: true #是否启用
    max-history: -1 #备份保留天数，-1为永久保留
    table-name: magic_api_backup #使用数据库存储备份时的表名
  response-code:
    success: 0 #执行成功的code值
    invalid: 1 #参数验证未通过的code值
    exception: 2 #执行出现异常的code值
  page:
    size: perPage # 页大小的参数名称
    page: page # 页码的参数名称
    default-page: 1 # 未传页码时的默认首页
    default-size: 10 # 未传页大小时的默认页大小

# 文件管理
files:
  local:
    enable: true
    base-path: /application/www
