spring:
  application:
    name: quick-boot-online
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.ip}:${nacos.port}
        namespace: ${nacos.namespace}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:classpath:${profiles.active}.properties
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:knife4j.yml
      - optional:nacos:mybatis-plus.yml
      - optional:nacos:logging.yml
      - optional:nacos:monitor.yml
      - optional:nacos:redis.yml
      - optional:nacos:sa-token.yml
